### ISSUE TITLE
FFmpeg.Avalonia Sample not working

### ISSUE THREAD

**Issue by Tammon23** [dove-team/FFmpegView#4]
Hello, 
I had some issues trying to get the sample to work. 

First off running the sample doesn't work right away, the compiler complains about playerView being null so I added 
` 
var playerView = this.FindControl<FFmpegView.FFmpegView>("playerView");
`
which seemed to appease it. But after running it, I see a blank window pop up but no media playing,

As far as I know I have all the correct packages installed and at the correct version.

I should also add that in the debug console I saw this: FFmpeg InitDecodecVideo Failed: Specified method is not supported. (FFmpegView #17625630)

**Comment by michael-eddy** [comment]
#5 fixed

**Comment by michael-eddy** [comment]
the version 2 is working on avalonia 11 and above only, if your avalonia is below 11 please use version 1.
and `FindControl` is now unnecessary after 11 it's declared XAML object name already,you just need use `playerView` on `x:Name` .

**Comment by Tammon23** [comment]
I found the cause of both the issues:

1. The issue where playerView was null was a precedence issue. Avalonia's auto-name-generator requires that InitializeComponent be called first before using any auto-generated properties. Because the auto-generated value was using in the InitializeComponent function it wasn't properly generated. Moving the logic to a different function and invoking it after InitialComponent resolved the issue without needing to use FindControl with Avalonia 11+.

2. The second issue was caused because the following silent exception
`
System.NotSupportedException: Specified method is not supported.
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_1267()
   at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_557()
   at FFmpeg.AutoGen.ffmpeg.avformat_alloc_context()
   at FFmpegView.VideoStreamDecoder.InitDecodecVideo(String uri)
`
I'm not sure of the fix to that though. As far as versioning goes I have all the same packages at the same version level listed here https://github.com/dove-team/FFmpegView/blob/main/samples/FFmpegView.AvaloniaDemo/FFmpegView.AvaloniaDemo.csproj

**Comment by Tammon23** [comment]
Update the System.NotSupportedException:

The reason why that exception was occurring was because of the following line

https://github.com/dove-team/FFmpegView/blob/50dff2d59252df976dae03294f472a02615a8934/src/FFmpegView.Shared/Core.cs#L41

My cpu is x64, however that wasn't an option only x86 (32-bit) and arm64 (mobile cpu). Downloading the correct x64 binaries resolved the exception but currently still no video.

**Comment by Tammon23** [comment]
Solved the final issue, so I'm closing this

**Comment by michael-eddy** [comment]
> Update the System.NotSupportedException:
> 
> The reason why that exception was occurring was because of the following line
> 
> https://github.com/dove-team/FFmpegView/blob/50dff2d59252df976dae03294f472a02615a8934/src/FFmpegView.Shared/Core.cs#L41
> 
> My cpu is x64, however that wasn't an option only x86 (32-bit) and arm64 (mobile cpu). Downloading the correct x64 binaries resolved the exception but currently still no video.

the fffmpeg build in x86_64,the mark name `win-x86` is just the name,but if that i can got the x86 and x64 libs,may change the cpu mark in later version.
